<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/**
 * @var \Amasty\RequestQuote\Block\Adminhtml\Items\Column\Name $block
 */
?>
<?php if ($item = $block->getItem()): ?>
    <div id="order_item_<?= /* @noEscape */ $item->getId() ?>_title"
         class="product-title">
        <?= $escaper->escapeHtml($item->getName()) ?>
    </div>

    <?php
        /* phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper */
        $skus = $this->helper(\Magento\Catalog\Helper\Data::class)->splitSku($escaper->escapeHtml($block->getSku()));
    ?>
    <div class="product-sku-block">
        <span><?= /* @noEscape */ __('SKU') ?>:</span>
        <?= /* @noEscape */ implode('<br />', $skus) ?>
    </div>

    <?php if ($block->getOrderOptions()): ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $option): ?>
                <dt><?= $escaper->escapeHtml($option['label']) ?>:</dt>
                <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= /* @noEscape */ $block->getCustomizedOptionValue($option) ?>
                    <?php else: ?>
                        <?php $option = $block->getFormattedOption($option['value']); ?>
                        <?= /* @noEscape */ $option['value'] ?><?php if (isset($option['remainder']) && $option['remainder']): ?><span id="<?= /* @noEscape */ $_dots = 'dots' . uniqid() ?>"> ...</span><span id="<?= /* @noEscape */ $_id = 'id' . uniqid() ?>"><?= /* @noEscape */ $option['remainder'] ?></span>
                            <script>
                                require(['prototype'], function() {
                                    $('<?= /* @noEscape */ $_id ?>').hide();
                                    $('<?= /* @noEscape */ $_id ?>').up().observe('mouseover', function(){$('<?= /* @noEscape */ $_id ?>').show();});
                                    $('<?= /* @noEscape */ $_id ?>').up().observe('mouseover', function(){$('<?= /* @noEscape */ $_dots ?>').hide();});
                                    $('<?= /* @noEscape */ $_id ?>').up().observe('mouseout',  function(){$('<?= /* @noEscape */ $_id ?>').hide();});
                                    $('<?= /* @noEscape */ $_id ?>').up().observe('mouseout',  function(){$('<?= /* @noEscape */ $_dots ?>').show();});
                                });
                            </script>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?= $escaper->escapeHtml($item->getDescription()) ?>
<?php endif; ?>
