version: '3.8'

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: magento_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - magento

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magento_php
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/magento.ini:ro
    depends_on:
      - mysql
      - elasticsearch
      - redis
    environment:
      - PHP_IDE_CONFIG=serverName=magento
    networks:
      - magento

  mysql:
    image: mysql:8.0
    container_name: magento_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/magento.cnf:ro
    networks:
      - magento

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: magento_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - magento

  redis:
    image: redis:6-alpine
    container_name: magento_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - magento

  mailhog:
    image: mailhog/mailhog:latest
    container_name: magento_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento

volumes:
  mysql_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  magento:
    driver: bridge
