<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/**  @var \Amasty\RequestQuote\Block\Product\Action  $block*/
?>
<button type="submit"
        title="<?= $escaper->escapeHtml($block->getButtonText()) ?>"
        class="amquote-addto-button action outline <?php if ($block->isCategoryPage()): ?>-small<?php endif;?> <?php if ($block->isGuest()): ?>-guest<?php endif;?>"
        data-amquote-js="addto-button"
        <?php if ($block->getIsLoggedButton()): ?>data-amquote-logged="logged-button"<?php endif;?>
        <?php if (!$block->isCategoryPage()): ?> id="product-addtoquote" <?php endif;?>
        <?php if ($block->isCategoryPage()): ?> style="display:none;" <?php endif;?> >
    <?= $escaper->escapeHtml($block->getButtonText()) ?>
</button>

<script type="text/x-magento-init">
    {
        "[data-amquote-js='addto-button']": {
            "Amasty_RequestQuote/js/product/addtoquote": {
                "addUrl": "<?= $escaper->escapeUrl($block->getAddUrl());?>",
                "isCategoryPage": "<?= /** @noEscape */ $block->isCategoryPage() ?>",
                "loggedIn": "<?= /** @noEscape */ $block->getLoggedIn() ?>"
            }
        }
    }
</script>
