<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $code => $total): ?>
    <?php if ($total->getBlockName()): ?>
        <?= $block->getChildHtml($total->getBlockName(), false) ?>
    <?php else: ?>
        <tr class="<?= $escaper->escapeHtmlAttr($code) ?>">
            <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
                <?php if ($total->getStrong()): ?>
                    <strong><?= $escaper->escapeHtml($total->getLabel()) ?></strong>
                <?php else: ?>
                    <?= $escaper->escapeHtml($total->getLabel()) ?>
                <?php endif ?>
            </th>
            <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $escaper->escapeHtmlAttr($total->getLabel()) ?>">
                <?php if ($total->getStrong()): ?>
                    <strong><?= /* @noEscape */ $block->formatValue($total) ?></strong>
                <?php else: ?>
                    <?= /* @noEscape */ $block->formatValue($total) ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach?>
