<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAylxlxs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAylxlxs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAylxlxs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAylxlxs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAylxlxs\appProdProjectContainer([
    'container.build_hash' => 'Aylxlxs',
    'container.build_id' => '10da7227',
    'container.build_time' => 1625817686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAylxlxs');
