<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php $item = $block->getItem() ?>
<?php $quote = $block->getItem()->getQuote() ?>
<tr>
    <td class="item-info has-extra">
        <p class="product-name"><?= $escaper->escapeHtml($item->getName()) ?></p>
        <p class="sku"><?= /* @noEscape */  __('SKU') ?>: <?= $escaper->escapeHtml($item->getSku()) ?></p>
        <?php if ($block->getOptionList()): ?>
            <dl>
                <?php foreach ($block->getOptionList() as $option): ?>
                    <dt><strong><em><?= $escaper->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd><?= /* @noEscape */  implode(',', $option['value']) ?></dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?= $escaper->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @noEscape */ $item->getQty() * 1 ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getUnitPriceHtml($item) ?>
    </td>
</tr>
