<html lang="fr-FR">
<head>
    <meta charset="utf-8">
    <style>
        body {
            padding: 50px;
        }
        div#logo {
            max-width: 10%;
            margin: 20px auto;
        }
        div#deuxiemeniveau{
        }
        .peauneuve {
            text-transform: uppercase;
            font-size: 2rem;
            color: #000157;
            text-align: center;
            margin-block-end: 0;
        }
        .containerContenu {
            width: 960px;
            margin: 0 auto;
            text-align: center;
        }
        .coordonnees {
            font-family : 'Poppins', serif;
            font-size: 1rem;
        }
    </style>
</head>
    <body>
        <div class="containerImg">
            <div id="logo">
                <img src="img/logo.png">
            </div>
            <div id="deuxiemeniveau">
                <p class="peauneuve">
                    Graphic-reseau est en maintenance...Nous revenons très vite
                </p>
            </div>
        </div>
        <div class="containerContenu">
            <br /><p>
            <div class="coordonnees">
                Vous pouvez nous contacter
                <br />
                <b>(+33) 01 64 85 11 06</b>
            </div>
            </p>
        </div>
    </body>
</html>
