<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<div class="admin__page-section-title">
    <span class="title"><?= /* @noEscape */ $block->getHeaderText() ?></span>
    <?php if ($block->getButtonsHtml()): ?>
        <div class="actions" style="float: right;"><?= $block->getButtonsHtml() ?></div>
    <?php endif; ?>
</div>

<?= $block->getChildHtml('', true) ?>
