<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php if ($block->getCanDisplayTotalRefunded()): ?>
<tr>
    <td class="label"><strong><?= /* @noEscape */ __('Total Refunded') ?></strong></td>
    <td class="emph"><?= /* @noEscape */ $block->displayPriceAttribute('total_refunded', true) ?></td>
</tr>
<?php endif; ?>
