<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<?php
/**
 * @var \Amasty\Rma\Block\Returns\NewReturn $block
 */

$returnOrder = $block->getReturnOrder();
$order = $returnOrder->getOrder();
if (!empty($returnOrder->getItems())): ?>
<form method="post" action="<?= $block->escapeUrl($block->getSaveUrl()) ?>" class="amrma-create-rma" data-mage-init='{"validation": {}}'>
    <input type="hidden" name="order" value="<?= (int)$order->getEntityId() ?>">
    <div class="amrma-customer-information">
        <div class="amrma-customer-name">
            <p>
                <span class="_strong">
                    <?= $block->escapeHtml(__('Customer name')) ?>:
                </span>
                <span class="amrma-name">
                    <?= $block->escapeHtml($order->getCustomerFirstname() . ' ' . $order->getCustomerLastname()) ?>
                </span>
            </p>
            <p>
                <span class="_strong">
                    <?= $block->escapeHtml(__('Email')) ?>:
                </span>
                <span class="amrma-email">
                    <?= $block->escapeHtml($order->getCustomerEmail()) ?>
                </span>
            </p>
        </div>
        <div class="amrma-customer-address">
            <p>
                <span class="_strong"><?= $block->escapeHtml(__('Customer Address')) ?></span>
            </p>
            <p>
                <?= /** @noEscape */ $block->getFormatAddress($order->getBillingAddress()) ?>
            </p>
        </div>
    </div>
    <div class="amrma-products-block">
        <h2 class="amrma-title"><?= $block->escapeHtml(__('Choose Items')) ?></h2>
        <div class="amrma-products-table">
            <?php foreach ($returnOrder->getItems() as $key => $item):
                $productItem = $item->getProductItem() ? : $item->getItem(); ?>
                <div class="amrma-product-item">
                    <div class="amrma-product">
                        <div class="amrma-checkbox-container">
                            <input type="checkbox" name="items[<?= (int)$item->getItem()->getItemId() ?>][return]" value="1" id="amrma-checkbox-<?= (int)$key ?>" class="amrma-checkbox amrma-return-item"<?= (!$item->isReturnable() ? ' disabled="true"' : '') ?> />
                            <label for="amrma-checkbox-<?= (int)$key ?>" class="amrma-label-container">
                                <span class="amrma-label"></span>
                                <span class="amrma-image">
                                    <img src="<?= $block->escapeUrl($block->getProductImage($item->getItem()->getItemId())) ?>"
                                         alt="<?= $block->escapeHtml($productItem->getName()) ?>"/>
                                </span>
                            </label>
                        </div>
                        <div class="amrma-product-information">
                            <strong class="amrma-item-name"><?= $block->escapeHtml($productItem->getName()) ?></strong>
                            <p class="_nomargin"><strong><?= $block->escapeHtml(__('SKU')) ?>: </strong><?= $block->escapeHtml($productItem->getSku()) ?></p>
                            <?php if ($options = $block->getAdditionalData($item)): ?>
                                <input type="checkbox" class="amrma-checkbox" id="amrma-show-more-<?= (int)$item->getItem()->getItemId(); ?>" />
                                <label for="amrma-show-more-<?= (int)$item->getItem()->getItemId(); ?>" class="amrma-showmore"><?= $block->escapeHtml(__('Details')) ?></label>
                                <div class="amrma-moreinfo">
                                    <?php foreach ($options as $option): ?>
                                        <p class="amrma-info">
                                            <strong><?= $block->escapeHtml($option['label']) ?>: </strong>
                                            <?php $optionValue = $block->getOptionValue($option) ?>
                                            <?php if (isset($optionValue['full_view'])): ?>
                                                <?= $block->escapeHtml($optionValue['full_view'], ['a']) ?>
                                            <?php else: ?>
                                                <?= $block->escapeHtml($optionValue['value'], ['a']) ?>
                                            <?php endif; ?>
                                        </p>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php if ($item->isReturnable()): ?>
                        <div class="amrma-product-message amrma-return-settings-container" style="display:none">
                            <div class="amrma-message-container -options">
                                <div class="amrma-return-qty">
                                    <label for="amrma-qty-select-<?= (int)$item->getItem()->getItemId() ?>" class="amrma-label"><?= $block->escapeHtml(__('Return Qty')) ?></label>
                                    <?php if ($item->getItem()->getIsQtyDecimal()): ?>
                                    <!-- TODO validate decimal -->
                                    <input id="amrma-qty-select-<?= (int)$item->getItem()->getItemId() ?>"
                                           name="items[<?= (int)$item->getItem()->getItemId() ?>][qty]"
                                           class="amrma-item-qty">
                                    <?php else: ?>
                                    <select id="amrma-qty-select-<?= (int)$item->getItem()->getItemId() ?>"
                                            class="amrma-select amrma-item-qty"
                                            name="items[<?= (int)$item->getItem()->getItemId() ?>][qty]">
                                        <?php
                                        $availableQty = $item->getAvailableQty();
                                        for ($itemCount = 1; $itemCount <= $availableQty; $itemCount++): ?>
                                            <option value="<?= (int)$itemCount ?>"><?= (int)$itemCount ?></option>
                                        <?php endfor; ?>
                                    </select>
                                    <?php endif; ?>
                                    <span class="amrma-total">/ <?= $block->escapeHtml($item->getAvailableQty()) ?></span>
                                </div>
                                <div class="amrma-return-select">
                                    <h4 class="amrma-title"><?= $block->escapeHtml(__('Return Reason')) ?></h4>
                                    <select class="amrma-select amrma-item-reason" name="items[<?= (int)$item->getItem()->getItemId() ?>][reason]">
                                        <option value=""><?= $block->escapeHtml(__('Please choose')) ?></option>
                                        <?php foreach ($block->getReasons() as $reason): ?>
                                            <option value="<?= (int)$reason->getReasonId() ?>" data-payer="<?= (int)$reason->getPayer() ?>">
                                                <?= $block->escapeHtml($reason->getLabel()) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="amrma-return-select">
                                    <h4 class="amrma-title"><?= $block->escapeHtml(__('Item Condition')) ?></h4>
                                    <select class="amrma-select amrma-item-condition" name="items[<?= (int)$item->getItem()->getItemId() ?>][condition]">
                                        <option value=""><?= $block->escapeHtml(__('Please choose')) ?></option>
                                        <?php foreach ($block->getConditions() as $condition): ?>
                                            <option value="<?= (int)$condition->getConditionId() ?>">
                                                <?= $block->escapeHtml($condition->getLabel()) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <div class="amrma-return-select">
                                    <h4 class="amrma-title"><?= $block->escapeHtml(__('Return Resolution')) ?></h4>
                                    <select class="amrma-select amrma-item-resolution" name="items[<?= (int)$item->getItem()->getItemId() ?>][resolution]">
                                        <option value=""><?= $block->escapeHtml(__('Please choose')) ?></option>
                                        <?php foreach ($item->getResolutions() as $resolution): ?>
                                            <option value="<?= (int)$resolution->getResolutionId() ?>">
                                                <?= $block->escapeHtml($resolution->getLabel()) ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                                <p class="amrma-shipping-payer amrma-message" style="display:none"></p>
                            </div>
                        </div>
                    <?php else: ?>
                        <?php
                        switch ($item->getNoReturnableReason()) {
                            case \Amasty\Rma\Model\OptionSource\NoReturnableReasons::ITEM_WASNT_SHIPPED:
                                ?>
                                <div class="amrma-product-message">
                                    <div class="amrma-message-container -gray">
                                        <p class="amrma-cause _nomargin">
                                            <?= $block->escapeHtml(__('This product wasn\'t shipped.')) ?>
                                        </p>
                                    </div>
                                </div>
                                <?php
                                break;
                            case \Amasty\Rma\Model\OptionSource\NoReturnableReasons::REFUNDED:
                                ?>
                                <div class="amrma-product-message">
                                    <div class="amrma-message-container -gray">
                                        <p class="amrma-cause _nomargin">
                                            <?= $block->escapeHtml(__('This product is already refunded.')) ?>
                                        </p>
                                        <?php
                                        if ($block->getConfig()->isShowAdministratorContact()) {
                                            echo $block->escapeHtml(__(
                                                ' If you have questions, please contact the store administrator:'
                                            ));
                                            if ($block->getConfig()->getAdministratorPhoneNumber()) {
                                                echo '<p class="amrma-phone _nomargin"><a href="tel:'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorPhoneNumber())
                                                    . '">' . $block->escapeHtml(
                                                        $block->getConfig()->getAdministratorPhoneNumber()
                                                    ) . '</a></p>';
                                            }
                                            if ($block->getConfig()->getAdministratorEmail()) {
                                                echo '<p class="amrma-adminmail _nomargin"><a href="mailto:'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorEmail()) . '">'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorEmail())
                                                    . '</a></p>';
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <?php
                                break;
                            case \Amasty\Rma\Model\OptionSource\NoReturnableReasons::ALREADY_RETURNED:
                                ?>
                                <div class="amrma-product-message">
                                    <div class="amrma-message-container -gray">
                                        <p class="amrma-cause _nomargin">
                                            <?= $block->escapeHtml(__('Rma request for this product is already created. Existing Return(s):')) ?>
                                        </p>
                                        <p class="_nomargin">
                                        <?php foreach ($item->getNoReturnableData() as $request): ?>
                                            <a href="<?= $block->escapeUrl($block->getRequestViewUrl($request)) ?>" target="_blank">
                                                #<?= $block->escapeHtml(str_pad($request[\Amasty\Rma\Api\Data\RequestInterface::REQUEST_ID], 9, '0', STR_PAD_LEFT)) ?>
                                            </a>
                                        <?php endforeach; ?>
                                        </p>
                                    </div>
                                </div>
                                <?php
                                break;
                            case \Amasty\Rma\Model\OptionSource\NoReturnableReasons::EXPIRED_PERIOD:
                                ?>
                                <div class="amrma-product-message">
                                    <div class="amrma-message-container -gray">
                                        <p class="amrma-cause _nomargin">
                                            <?= $block->escapeHtml(__('The return for this product can\'t be processed.')) ?>
                                        </p>
                                        <p class="amrma-warning-message _nomargin">
                                            <?= $block->escapeHtml(__('The return period expired.')) ?>
                                        </p>
                                        <?php
                                        if ($block->getConfig()->isShowAdministratorContact()) {
                                            echo $block->escapeHtml(__(
                                                ' If you have questions, please contact the store administrator:'
                                            ));
                                            if ($block->getConfig()->getAdministratorPhoneNumber()) {
                                                echo '<p class="amrma-phone _nomargin"><a href="tel:'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorPhoneNumber())
                                                    . '">' . $block->escapeHtml(
                                                        $block->getConfig()->getAdministratorPhoneNumber()
                                                    ) . '</a></p>';
                                            }
                                            if ($block->getConfig()->getAdministratorEmail()) {
                                                echo '<p class="amrma-adminmail _nomargin"><a href="mailto:'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorEmail()) . '">'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorEmail())
                                                    . '</a></p>';
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <?php
                                break;
                            case \Amasty\Rma\Model\OptionSource\NoReturnableReasons::ITEM_WAS_ON_SALE:
                                ?>
                                <div class="amrma-product-message">
                                    <div class="amrma-message-container -gray">
                                        <p class="amrma-cause _nomargin">
                                            <?= $block->escapeHtml(__('This product cannot be returned.')) ?>
                                        </p>
                                        <p class="amrma-warning-message _nomargin">
                                            <?= $block->escapeHtml(__('This product was on sale.')) ?>
                                        </p>
                                        <?php
                                        if ($block->getConfig()->isShowAdministratorContact()) {
                                            echo $block->escapeHtml(__(
                                                ' If you have questions, please contact the store administrator:'
                                            ));
                                            if ($block->getConfig()->getAdministratorPhoneNumber()) {
                                                echo '<p class="amrma-phone _nomargin"><a href="tel:'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorPhoneNumber())
                                                    . '">' . $block->escapeHtml(
                                                        $block->getConfig()->getAdministratorPhoneNumber()
                                                    ) . '</a></p>';
                                            }
                                            if ($block->getConfig()->getAdministratorEmail()) {
                                                echo '<p class="amrma-adminmail _nomargin"><a href="mailto:'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorEmail()) . '">'
                                                    . $block->escapeHtml($block->getConfig()->getAdministratorEmail())
                                                    . '</a></p>';
                                            }
                                        }
                                        ?>
                                    </div>
                                </div>
                                <?php
                                break;
                        }
                        ?>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <?php if ($customFields = $block->getConfig()->getCustomFields()): ?>
            <div class="amrma-bank-details">
                <h2 class="amrma-title">
                    <?= $block->escapeHtml($block->getConfig()->getCustomFieldsLabel()) ?>
                </h2>
                <?php foreach ($customFields as $code => $label): ?>
                    <div class="amrma-input-block">
                        <label class="amrma-title" for="custom_field_<?= $block->escapeHtml($code) ?>">
                            <?= $block->escapeHtml($label) ?>
                        </label>
                        <input id="custom_field_<?= $block->escapeHtml($code) ?>" type="text"
                               name="custom_fields[<?= $block->escapeHtml($code) ?>]"
                               class="amrma-field" />
                    </div>
                <?php endforeach; ?>
            </div>

        <?php endif; ?>
        <div class="amrma-comment-block">
            <h2 class="amrma-title"><?= $block->escapeHtml(__('Message')) ?></h2>
            <p class="_nomargin amrma-img-text">
                <?= $block->escapeHtml(__('Please do not forget to take a picture of the goods from all sides. Request without such photos may not be approved')) ?>
            </p>
            <textarea name="comment" class="amrma-comment" id="" cols="30" rows="5" placeholder="<?= $block->escapeHtml(__(' Please, describe the issue in details.')) ?>"></textarea>
            <div class="amrma-attach-file" data-amrma-js="file-container">
                <label for="amrma-attach" class="amrma-label"><?= $block->escapeHtml(__('Attach File')) ?></label>
                <input type="file"
                       id="amrma-attach"
                       accept=".pdf,.png,.jpg,.gif"
                       multiple
                       class="amrma-attach"
                />
                <input type="hidden" name="attach-files" id="amrma-attached-files" data-amrma-js="file-input"/>
            </div>
            <?php if ($block->getConfig()->isReturnPolicyEnabled()): ?>
            <div class="amrma-return-policy">
                <div class="amrma-checkbox-container -policy">
                    <input class="amrma-checkbox"
                           type="checkbox"
                           id="amrma-checkbox-policy"
                           name="rmapolicy"
                           value="1"
                           data-amrma-js="policy"
                    />
                    <label for="amrma-checkbox-policy" class="amrma-label"></label>
                </div>
                <p class="amrma-text">
                    <?= /** @noEscape */ str_replace(['%1', '%2'], ['<a href="' . $block->getPolicyUrl() . '" target="_blank">', '</a>'], $block->escapeHtml(__('I have read and accept the %1Return Policy%2'))) ?> <span style="color: #e02b27">*</span>
                </p>
            </div>
            <?php endif; ?>
            <div class="amrma-btns-block">
                <button class="btn amreturn-btn" type="submit"><?= $block->escapeHtml(__('Submit Request')) ?></button>
                <a href="<?= $block->escapeUrl($block->getHistoryUrl()) ?>" class="amrma-link-cancel"><?= $block->escapeHtml(__('Cancel')) ?></a>
            </div>
        </div>
    </div>
</form>
<script>
    require(['jquery', 'Magento_Ui/js/modal/alert', 'domReady!'], function ($, message) {
        $('.amrma-checkbox:checked').each(function () {
            $(this).closest('.amrma-product-item').find('.amrma-return-settings-container').show()
        });
        $('.amrma-return-item').click(function () {
            if ($(this).is(':checked')) {
                $(this).closest('.amrma-product-item').find('.amrma-return-settings-container').show()
            } else {
                $(this).closest('.amrma-product-item').find('.amrma-return-settings-container').hide()
            }
        });
        $('.amrma-create-rma').submit(function (e) {
            var errors = '';
            if ($('.amrma-return-item:checked').length === 0) {
                errors += '<?= $block->escapeHtml(__('Items were not selected')) ?>' + '. ';
            } else {
                $('.amrma-return-item:checked').each(function () {
                    var itemContainer = $(this).closest('.amrma-product-item'),
                        mContainer = itemContainer.find('.amrma-message-container');
                    mContainer.removeClass('-failed');
                    if (itemContainer.find('.amrma-item-reason').val() == '') {
                        errors += '<?= $block->escapeHtml(__('Please Select Reason for')) ?>' + ' ' + itemContainer.find('.amrma-item-name').text() + '. ';
                        mContainer.addClass('-failed');
                    }
                    if (itemContainer.find('.amrma-item-condition').val() == '') {
                        errors += '<?= $block->escapeHtml(__('Please Select Condition for')) ?>' + ' ' + itemContainer.find('.amrma-item-name').text() + '. ';
                        mContainer.addClass('-failed');
                    }

                    if (itemContainer.find('.amrma-item-resolution').val() == '') {
                        errors += '<?= $block->escapeHtml(__('Please Select Resolution for')) ?>' + ' ' + itemContainer.find('.amrma-item-name').text() + '. ';
                        mContainer.addClass('-failed');
                    }

                    var qty = itemContainer.find('.amrma-item-qty').val();
                    if (itemContainer.find('.amrma-item-qty').val() == '' || parseFloat(qty) < 0.001) {
                        errors += '<?= $block->escapeHtml(__('Please Select Qty for')) ?>' + ' ' + itemContainer.find('.amrma-item-name').text() + '. ';
                        mContainer.addClass('-failed');
                    }
                });
            }

            if ($('[data-amrma-js="policy"]').length && !$('[data-amrma-js="policy"]:checked').length) {
                errors += '<?= $block->escapeHtml(__('Please accept the Return Policy')) ?>' + '. ';
                $('[data-amrma-js="policy"]').on('click', function () {
                    $(this).closest('.amrma-return-policy').removeClass('-border');
                }).closest('.amrma-return-policy').addClass('-border');
            }

            if (errors.length) {
                message({content: errors});
                e.preventDefault();
            }
        });

        $('#amrma-attach').change(function () {
            var formData = new FormData(),
                filesFromForm = $(this)[0].files;
            $.each(filesFromForm, function (i, file) {
                formData.append(file.name.substr(0, file.name.lastIndexOf('.')), file);
            });
            $.ajax({
                showLoader: true,
                url: "<?= $block->escapeUrl($block->getChatUploadUrl()) ?>",
                processData: false,
                contentType: false,
                global: false,
                data: formData,
                method: "POST",
                dataType: "text",
                success: function (result) {
                    var value;
                    if (result.length) {
                        showFileNames(JSON.parse(result));

                        if ($('#amrma-attached-files').val() != '') {
                            value = JSON.stringify(JSON.parse($('#amrma-attached-files').val()).concat(JSON.parse(result)));
                        } else {
                            value = result;
                        }
                        $('#amrma-attached-files').val(value);
                    }
                }
            });
        });

        function showFileNames(files) {
            for (var i = 0; i < files.length; i++) {
                var $container = $('<div>', {class : 'amrma-chat-file -newreturn'}),
                    $fileName = $('<span>', {class : 'amrma-file'}),
                    $link = $('<span>', {class : 'amrma-file amrma-delete'});

                $fileName.text(files[i].filename);
                $container.data('filehash', files[i].filehash);
                $container.data('extension', files[i].extension);
                $container.append($fileName);
                $container.append($link);
                $link.on('click', deleteFile);
                $('[data-amrma-js="file-container"]').append($container);
            }
        }

        function deleteFile(e) {
            var fileNameContainer = $(e.currentTarget).parent(),
                postData = {},
                $filesInput = $('[data-amrma-js="file-input"]'),
                attachedFiles;

            postData.filehash = fileNameContainer.data('filehash');
            postData.extension = fileNameContainer.data('extension');

            $.ajax({
                url: "<?= $block->escapeUrl($block->getChatDeleteUrl()) ?>",
                data: {file: postData},
                method: 'post',
                global: false,
                dataType: 'json',
                success: function (data) {
                    attachedFiles = JSON.parse($filesInput.val());
                    attachedFiles = attachedFiles.filter(function (file) {
                       return file.filehash !== postData.filehash;
                    });
                    $filesInput.val(JSON.stringify(attachedFiles));
                    fileNameContainer.remove();
                }.bind(this)
            });
        }

        $('.amrma-item-reason').change(function () {
            switch ($(this).find('option:selected').data('payer')) {
                case <?= (int)\Amasty\Rma\Model\OptionSource\ShippingPayer::CUSTOMER ?>:
                    $(this).closest('.amrma-message-container').find('.amrma-shipping-payer').show().text('<?= $block->escapeHtml(__('You are supposed to cover shipping costs')) ?>');
                    break;
                case <?= (int)\Amasty\Rma\Model\OptionSource\ShippingPayer::STORE_OWNER ?>:
                    $(this).closest('.amrma-message-container').find('.amrma-shipping-payer').show().text('<?= $block->escapeHtml(__('Store is supposed to cover shipping costs')) ?>');
                    break;
                default:
                    $(this).closest('.amrma-message-container').find('.amrma-shipping-payer').hide();
            }
        });
    });
</script>
<?php else: ?>
    <h2 class="amrma-title"><?= $block->escapeHtml(__('There are no items to return.')) ?></h2>
<?php endif; ?>
