<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<?php
/**
 * @var \Amasty\Rma\Block\Returns\OrderList $block
 */

if ($orders = $block->getOrders()): ?>
    <div class="amreturns-order-select">
        <div class="amreturns-title-container">
            <span class="amreturns-select-title"><?= $block->escapeHtml(__('Create new return request')) ?></span>
        </div>
        <div class="amreturns-orders-container">
            <select name="amreturns-orders-select" class="amreturn-select" id="amreturn-order">
                <?php foreach ($orders as $order): ?>
                    <option value="<?= $block->escapeHtml($order[\Magento\Sales\Api\Data\OrderInterface::ENTITY_ID]); ?>">
                        <?= $block->escapeHtml(__('Order #') . $order[\Magento\Sales\Api\Data\OrderInterface::INCREMENT_ID]) ?> -
                        <?= $block->escapeHtml($block->formatDate($order[\Magento\Sales\Api\Data\OrderInterface::CREATED_AT])); ?> -
                        <?= $block->escapeHtml($block->formatPrice($order[\Magento\Sales\Api\Data\OrderInterface::GRAND_TOTAL])); ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <button class="btn amreturn-btn" data-amrma-js="return-btn" title="<?= $block->escapeHtml(__('Return')) ?>"
                onclick="location.href='<?= $block->escapeUrl($block->getNewReturnUrl()); ?>order/' + document.getElementById('amreturn-order').value">
                <?= $block->escapeHtml(__('Return')) ?>
            </button>
            <?php if ($block->isGuest()): ?>
                <button class="btn amreturn-btn" data-amrma-js="return-btn" title="<?= $block->escapeHtml(__('Other Order Return')) ?>"
                        onclick="location.href='<?= $block->escapeUrl($block->getLogoutUrl()); ?>'">
                    <?= $block->escapeHtml(__('Logout')) ?>
                </button>
            <?php endif; ?>
        </div>
    </div>
<?php elseif ($block->isGuest()): ?>
    <button class="btn amreturn-btn" data-amrma-js="return-btn" title="<?= $block->escapeHtml(__('Other Order Return')) ?>"
            onclick="location.href='<?= $block->escapeUrl($block->getLogoutUrl()); ?>'">
        <?= $block->escapeHtml(__('Other Order Return')) ?>
    </button>
<?php endif ?>
