<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/**
 * Template for \Magento\Backend\Block\Widget\Grid
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 *
 */
/** @var \Magento\Framework\Escaper $escaper */
/* @var $block \Magento\Backend\Block\Widget\Grid */
$numColumns = count($block->getColumns());
?>
<?php if ($block->getCollection()): ?>

<?php if ($block->canDisplayContainer()): ?>
<div id="<?= $escaper->escapeHtml($block->getId()) ?>" data-grid-id="<?= $escaper->escapeHtml($block->getId()) ?>">
<?php else: ?>
<?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<?php endif; ?>

        <div class="admin__data-grid-header admin__data-grid-toolbar">
            <?php $massActionAvailable = $block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable() ?>
            <?php if ($block->getPagerVisibility() || $block->getExportTypes() || $block->getChildBlock('grid.columnSet')->getFilterVisibility() || $massActionAvailable): ?>
            <div class="admin__data-grid-header-row">
                <?php if ($massActionAvailable): ?>
                    <?= $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : '' ?>
                <?php endif; ?>

                <?php if ($block->getChildBlock('grid.export')): ?>
                    <?= $block->getChildHtml('grid.export') ?>
                <?php endif; ?>
            </div>
            <?php endif; ?>
            <div class="<?= /* @noEscape */ $massActionAvailable ? '_massaction ': '' ?> admin__data-grid-header-row">
                <?php if ($massActionAvailable): ?>
                    <?= $block->getChildHtml('grid.massaction') ?>
                <?php else: ?>
                    <?= $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : '' ?>
                <?php endif; ?>
                    <?php $countRecords = $block->getCollection()->getSize(); ?>
                    <div class="admin__control-support-text">
                        <span id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>-total-count" <?= /* @noEscape */ $block->getUiId('total-count') ?>>
                            <?= /* @noEscape */ $countRecords ?>
                        </span>
                        <?= /* @noEscape */ __('records found') ?>
                        <span id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_massaction-count"
                              class="mass-select-info _empty"><strong data-role="counter">0</strong> <span><?= /* @noEscape */ __('selected') ?></span></span>
                    </div>
                <?php if ($block->getPagerVisibility()): ?>
                    <div class="admin__data-grid-pager-wrap">
                        <select name="<?= /* @noEscape */ $block->getVarNameLimit() ?>"
                                id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_page-limit"
                                onchange="<?= /* @noEscape */ $block->getJsObjectName() ?>.loadByElement(this)" <?= /* @noEscape */ $block->getUiId('per-page') ?>
                                class="admin__control-select">
                            <option value="20"<?php if ($block->getCollection()->getPageSize() == 20): ?>
                                selected="selected"<?php endif; ?>>20
                            </option>
                            <option value="30"<?php if ($block->getCollection()->getPageSize() == 30): ?>
                                selected="selected"<?php endif; ?>>30
                            </option>
                            <option value="50"<?php if ($block->getCollection()->getPageSize() == 50): ?>
                                selected="selected"<?php endif; ?>>50
                            </option>
                            <option value="100"<?php if ($block->getCollection()->getPageSize() == 100): ?>
                                selected="selected"<?php endif; ?>>100
                            </option>
                            <option value="200"<?php if ($block->getCollection()->getPageSize() == 200): ?>
                                selected="selected"<?php endif; ?>>200
                            </option>
                        </select>
                        <label for="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_page-limit"
                            class="admin__control-support-text"><?= /* @noEscape */ __('per page') ?></label>
                        <div class="admin__data-grid-pager">
                            <?php $curPage = $block->getCollection()->getCurPage() ?>
                            <?php $lastPage = $block->getCollection()->getLastPageNumber() ?>

                            <?php if ($curPage > 1): ?>
                                <button class="action-previous"
                                        type="button"
                                        onclick="<?= /* @noEscape */ $block->getJsObjectName() ?>.setPage('<?= /* @noEscape */ ($curPage - 1) ?>');return false;">
                                            <span><?= /* @noEscape */ __('Previous page') ?></span>
                                </button>
                            <?php else: ?>
                                <button type="button" class="action-previous disabled"><span><?= /* @noEscape */ __('Previous page') ?></span></button>
                            <?php endif; ?>

                            <input type="text"
                                   id="<?= $escaper->escapeHtml($block->getHtmlId()) ?>_page-current"
                                   name="<?= /* @noEscape */ $block->getVarNamePage() ?>"
                                   value="<?= /* @noEscape */ $curPage ?>"
                                   class="admin__control-text"
                                   onkeypress="<?= /* @noEscape */ $block->getJsObjectName() ?>.inputPage(event, '<?= /* @noEscape */ $lastPage ?>')" <?= /* @noEscape */ $block->getUiId('current-page') ?> />

                            <label class="admin__control-support-text" for="<?= $escaper->escapeHtml($block->getHtmlId())
                            ?>_page-current">
                                <?= /* @noEscape */ __('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>') ?>
                            </label>
                            <?php if ($curPage < $lastPage): ?>
                                <button title="<?= /* @noEscape */ __('Next page') ?>"
                                        class="action-next"
                                        onclick="<?= /* @noEscape */ $block->getJsObjectName() ?>.setPage('<?= /* @noEscape */ ($curPage + 1) ?>');return false;">
                                    <span><?= /* @noEscape */ __('Next page') ?></span>
                                </button>
                            <?php else: ?>
                                <button type="button" class="action-next disabled"><span><?= /* @noEscape */ __('Next page') ?></span></button>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </div>
        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <?php if ($block->getGridCssClass()): ?>
            <table class="<?= /* @noEscape */ $block->getGridCssClass() ?> data-grid" id="<?= $escaper->escapeHtml($block->getId()) ?>_table">
                <!-- Rendering column set -->
                <?= $block->getChildHtml('grid.columnSet') ?>
            </table>
        <?php else: ?>

            <table class="data-grid" id="<?= $escaper->escapeHtml($block->getId()) ?>_table">
                <!-- Rendering column set -->
                <?= $block->getChildHtml('grid.columnSet') ?>
            </table>

            <?php if ($block->getChildBlock('grid.bottom.links')): ?>
                <?= $block->getChildHtml('grid.bottom.links') ?>
            <?php endif; ?>

        <?php endif ?>
        </div>
<?php if ($block->canDisplayContainer()): ?>
</div>
<script>
    var deps = [];

    <?php if ($block->getDependencyJsObject()): ?>
    deps.push('uiRegistry');
    <?php endif; ?>


    deps.push('Amasty_RequestQuote/quote/edit/form');
    deps.push('jquery');


    deps.push('mage/adminhtml/grid');

    require(deps, function(<?= ($block->getDependencyJsObject() ? 'registry' : '') ?>){
        <?php //TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed ?>

        <?php if ($block->getDependencyJsObject()): ?>
            registry.get('<?= /* @noEscape */ $block->getDependencyJsObject() ?>', function (<?= /* @noEscape */ $block->getDependencyJsObject() ?>) {
        <?php endif; ?>

        <?= /* @noEscape */ $block->getJsObjectName() ?> = new varienGrid('<?= $escaper->escapeHtml($block->getId()) ?>', '<?= /* @noEscape */ $block->getGridUrl() ?>', '<?= /* @noEscape */ $block->getVarNamePage() ?>', '<?= /* @noEscape */ $block->getVarNameSort() ?>', '<?= /* @noEscape */ $block->getVarNameDir() ?>', '<?= /* @noEscape */ $block->getVarNameFilter() ?>');
        <?= /* @noEscape */ $block->getJsObjectName() ?>.useAjax = <?= /* @noEscape */ $block->getUseAjax() ? 'true' : 'false' ?>;
        <?php if ($block->getRowClickCallback()): ?>
        <?= /* @noEscape */ $block->getJsObjectName() ?>.rowClickCallback = <?= /* @noEscape */ $block->getRowClickCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getCheckboxCheckCallback()): ?>
        <?= /* @noEscape */ $block->getJsObjectName() ?>.checkboxCheckCallback = <?= /* @noEscape */ $block->getCheckboxCheckCallback() ?>;
        <?php endif; ?>
        <?php if ($block->getSortableUpdateCallback()): ?>
        <?= /* @noEscape */ $block->getJsObjectName() ?>.sortableUpdateCallback = <?= /* @noEscape */ $block->getSortableUpdateCallback() ?>;
        <?php endif; ?>
        <?= /* @noEscape */ $block->getJsObjectName() ?>.bindSortable();
        <?php if ($block->getRowInitCallback()): ?>
        <?= /* @noEscape */ $block->getJsObjectName() ?>.initRowCallback = <?= /* @noEscape */ $block->getRowInitCallback() ?>;
        <?= /* @noEscape */ $block->getJsObjectName() ?>.initGridRows();
        <?php endif; ?>
        <?php if ($block->getChildBlock('grid.massaction') && $block->getChildBlock('grid.massaction')->isAvailable()): ?>
        <?= /* @noEscape */ $block->getChildBlock('grid.massaction')->getJavaScript() ?>
        <?php endif ?>
        <?= /* @noEscape */ $block->getAdditionalJavaScript() ?>

        <?php if ($block->getDependencyJsObject()): ?>
            });
        <?php endif; ?>
    });
</script>
<?php endif; ?>

<?php if ($block->getChildBlock('grid.js')): ?>
    <?= $block->getChildHtml('grid.js') ?>
<?php endif; ?>

<?php endif ?>
