<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_MauticIntegration
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>
<?php
/** @var  $block \Ced\MauticIntegration\Block\Adminhtml\Setting\Edit\Tabs\Contact */
$status = $block->getConnectionStatus();
$elements = $block->getContactProperty();
$odd = '';
?>
<?php if ($status) { ?>
<div class="contect-table-wrapper">
    <table class="data-grid" id="tiers_table">
        <thead>
            <tr>
                <th class="data-grid-th">
                    <?php /* @escapeNotVerified */ echo __('Contact Property Name') ?>
                </th>
                <th class="data-grid-th">
                    <?php /* @escapeNotVerified */ echo __('Action') ?>
                </th>
            </tr>
        </thead>
        <tbody id="_container">
            <?php foreach ($elements as $element) { ?>
                <tr class="<?php echo $odd; ?>">
                <td class="col-customer-group">
                    <?php /* @escapeNotVerified */ echo $element->getName(); ?>
                </td>
                <?php if ($element->getMauticId()) { ?>
                <td class="col-delete">
                    <i class="fa fa-check"></i>
                </td>
                <?php } else { ?>
                <td class="col-delete">
                    <?php /* @escapeNotVerified */ echo '<button type="button" title="create" 
                    class="action-default scalable property-create" 
                        id="'.$element->getCode().'" data-property-code="'.$element->getCode().'">Create</button>' ?>
                </td>
                <?php } ?>
            </tr>
            <?php $odd = ($odd == '_odd-row') ? '': '_odd-row';} ?>
        </tbody>
    </table>



</div>
<?php } else { ?>
    <div class="control">
    <div class="col-m-6">
        <div class="connection-status disconnected">
            <div class="icon"><i class="fa fa-close"></i></div>
            <span class="item-title"><?php echo __('Connection Status'); ?></span>
            <span class="item-description"><?php echo __('Not Connected'); ?></span>
        </div>
    </div>
    </div>
<?php } ?>
