<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_MauticIntegration
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
/** @var  $block \Ced\MauticIntegration\Block\Adminhtml\Setting\Edit\Tabs\JsBlock */ ?>
<script type="text/x-magento-init">
     {
        "*" :{
        "Ced_MauticIntegration/js/contact" : {
           "Type" : "<?php echo \Ced\MauticIntegration\Model\CedMautic::TYPE_PROPERTY; ?>",
           "PropertyCreateAjaxUrl" : "<?php /* @escapeNotVerified */
    echo $block->getAjaxUrl(); ?>"
                 }
             }
        }

</script>

<script type="text/x-magento-init">
     {
        "*" :{
        "Ced_MauticIntegration/js/segment":{
           "Type" : "<?php echo \Ced\MauticIntegration\Model\CedMautic::TYPE_SEGMENT; ?>",
           "SegmentCreateAjaxUrl" : "<?php /* @escapeNotVerified */
    echo $block->getAjaxUrl(); ?>"
                 }
             }
        }


</script>