<?php /** @var $block Colissimo\Shipping\Block\Adminhtml\Order\Create\Pickup */ ?>
<script>
    var colissimoPickupMethod = '<?php echo $block->getPickupMethod() ?>';
    var colissimoPickupSelectorId = 'order-' + colissimoPickupMethod;

    require(["jquery", "Magento_Sales/order/create/form"], function($) {
        (function(prepareArea) {
            order.prepareArea = function (area) {
                if (area.includes('shipping_method')) {
                    area.push(colissimoPickupMethod);
                    order.addColissimoContainer();
                }
                return prepareArea.call(this, area);
            }
        }(order.prepareArea));

        order.setColissimoPickup = function (pickup) {
            var data = {};
            data['colissimo[pickup]'] = pickup;
            data['order[shipping_method]'] = colissimoPickupMethod;
            this.loadArea(['shipping_method', 'totals', 'billing_method'], true, data);
        };

        order.addColissimoContainer = function() {
            var pickupElement = $('#' + colissimoPickupSelectorId);
            if (!pickupElement.length) {
                $('#order-shipping_method').after(
                    '<div id="' + colissimoPickupSelectorId + '" class="admin__page-section-item colissimo-pickup-selector"></div>'
                );
            }
        };

        <?php if ($block->canLoad()): ?>
            order.addColissimoContainer();
            $(window).load(function() {
                order.loadArea([colissimoPickupMethod], true, {});
            });
        <?php endif; ?>
    });
</script>