<?php
/**
 * Copyright © Lyra Network.
 * This file is part of Systempay plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$oneClickActive = $block->isOneClickActive(); // 1-Click enabled?
$customer = $block->getCurrentCustomer(); // Logged in customer.
?>

<ul class="form-list"
    id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
    style="display:none;">
<?php
if ($block->isLocalCcType()) :
    $cards = $block->getAvailableCcTypes();
    $single = count($cards) === 1;

    // Show card logos as radio buttons.
    $amexCards = '';
    $cbCards = '';
    $otherCards = '';

    $first = true;
    foreach ($cards as $code => $label) {
        $html = '<div class="systempay-card">';

        if ($single) {
            $html .= '<input type="hidden" id="systempay_standard_cc_type_' . $block->escapeHtml($code)
                . '" value="' . $block->escapeHtml($code) . '" name="payment[systempay_standard_cc_type]" />' ;
        } else {
            $html .= '<input type="radio" class="radio" id="systempay_standard_cc_type_' . $block->escapeHtml($code)
                . '"' . ($first ? ' checked="checked"' : '') . ' value="'
                . $block->escapeHtml($code) . '" name="payment[systempay_standard_cc_type]" />' ;
        }

        $first = false;
        $ccImageSrc = $block->getCcTypeImageSrc($code);

        $label = $ccImageSrc ? '<img alt="' . $block->escapeHtml($label) . '"
                                     src="' . $block->escapeHtml($ccImageSrc) . '"
                                     title="' . $block->escapeHtml($label) . '" />'
                : "<span>" . $block->escapeHtml($label) . "</span>";

        $html .= '<label for="systempay_standard_cc_type_' . $block->escapeHtml($code) . '">'
                    . $label .
                  '</label>';
        $html .= '</div>';

        $network = $block->getCcTypeNetwork($code);
        if ($network === 'AMEX') {
            $amexCards .= $html;
        } elseif ($network === 'CB') {
            $cbCards .= $html;
        } else {
            $otherCards .= $html;
        }
    }

    if ($cbCards != '') {
        echo '<li class="systempay-standard-cc-block">' . $cbCards . '</li>';
    }
    if ($amexCards != '') {
        echo '<li class="systempay-standard-cc-block">' . $amexCards . '</li>';
    }
    if ($otherCards != '') {
        echo '<li class="systempay-standard-cc-block">' . $otherCards . '</li>';
    }
endif;

if ($oneClickActive && $customer && $customer->getCustomAttribute('systempay_identifier')) : ?>
        <li class="systempay-standard-cc-block">
            <?php echo $block->escapeHtml(__('You will enter payment data after order confirmation.')); ?>
        </li>
        <li class="systempay-standard-cc-block">
            <span class="or"><?php echo $block->escapeHtml(__('OR')); ?></span>
        </li>

        <li class="systempay-standard-cc-block">
            <a class="systempay-payment-link" href="javascript: void(0);"
                onclick="javascript: systempayUpdatePaymentBlock('id');">
                <?php echo $block->escapeHtml(__('Click here to pay with your stored means of payment.')); ?>
            </a>
        </li>

        <!-- Payment with registered card block. -->
        <li class="systempay-standard-id-block">
            <input type="hidden" value="1" name="payment[systempay_standard_use_identifier]" />
            <span>
                <?php echo $block->escapeHtml(__('You will pay with your stored means of payment %s.')); ?>
            </span>
        </li>

        <li class="systempay-standard-id-block">
            <span class="or"><?php echo $block->escapeHtml(__('OR')); ?></span>
        </li>

        <li class="systempay-standard-id-block">
            <a class="systempay-payment-link" href="javascript: void(0);"
                onclick="javascript: systempayUpdatePaymentBlock('cc');">
                <?php echo $block->escapeHtml(__('Click here to pay with another means of payment.')); ?>
            </a>
        </li>
<?php endif; ?>
</ul>

<?php if ($oneClickActive && $customer && $customer->getCustomAttribute('systempay_identifier')) : ?>
<script>
    require([
        'prototype'
    ], function() {
        // Display payment by identifier block when standard payment is selected.
        Event.stopObserving('p_method_systempay_standard', 'click', onMethodSystempayStandardClick);
        Event.observe('p_method_systempay_standard', 'click', onMethodSystempayStandardClick);

        systempayUpdatePaymentBlock.delay(0.2, 'id');
    });
</script>
<?php endif;?>