<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'grapesjsbuilder.event.assets.subscriber' shared service.

return $this->services['grapesjsbuilder.event.assets.subscriber'] = new \MauticPlugin\GrapesJsBuilderBundle\EventSubscriber\AssetsSubscriber(${($_ = isset($this->services['grapesjsbuilder.config']) ? $this->services['grapesjsbuilder.config'] : $this->load('getGrapesjsbuilder_ConfigService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.install.service']) ? $this->services['mautic.install.service'] : $this->load('getMautic_Install_ServiceService.php')) && false ?: '_'});
