<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'grapesjsbuilder.integration.configuration' shared service.

return $this->services['grapesjsbuilder.integration.configuration'] = new \MauticPlugin\GrapesJsBuilderBundle\Integration\Support\ConfigSupport();
