<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'grapesjsbuilder.config' shared service.

return $this->services['grapesjsbuilder.config'] = new \MauticPlugin\GrapesJsBuilderBundle\Integration\Config(${($_ = isset($this->services['mautic.integrations.helper']) ? $this->services['mautic.integrations.helper'] : $this->getMautic_Integrations_HelperService()) && false ?: '_'});
