<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'grapesjsbuilder.event.email.subscriber' shared service.

return $this->services['grapesjsbuilder.event.email.subscriber'] = new \MauticPlugin\GrapesJsBuilderBundle\EventSubscriber\EmailSubscriber(${($_ = isset($this->services['grapesjsbuilder.config']) ? $this->services['grapesjsbuilder.config'] : $this->load('getGrapesjsbuilder_ConfigService.php')) && false ?: '_'}, ${($_ = isset($this->services['grapesjsbuilder.model']) ? $this->services['grapesjsbuilder.model'] : $this->load('getGrapesjsbuilder_ModelService.php')) && false ?: '_'});
