<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.fixture.categorizedleadlists' shared service.

return $this->services['mautic.lead.fixture.categorizedleadlists'] = new \Mautic\LeadBundle\DataFixtures\ORM\LoadCategorizedLeadListData(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'});
