<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.cache.clear_cache_subscriber' shared service.

return $this->services['mautic.cache.clear_cache_subscriber'] = new \Mautic\CacheBundle\EventListener\CacheClearSubscriber(${($_ = isset($this->services['mautic.cache.provider']) ? $this->services['mautic.cache.provider'] : $this->load('getMautic_Cache_ProviderService.php')) && false ?: '_'}, ${($_ = isset($this->services['monolog.logger.mautic']) ? $this->services['monolog.logger.mautic'] : $this->getMonolog_Logger_MauticService()) && false ?: '_'});
