<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.dashboard.widget' shared service.

return $this->services['mautic.dashboard.widget'] = new \Mautic\DashboardBundle\Dashboard\Widget(${($_ = isset($this->services['mautic.dashboard.model.dashboard']) ? $this->services['mautic.dashboard.model.dashboard'] : $this->load('getMautic_Dashboard_Model_DashboardService.php')) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.user']) ? $this->services['mautic.helper.user'] : $this->getMautic_Helper_UserService()) && false ?: '_'}, ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'});
