<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.integrations.helper.config_integrations' shared service.

$this->services['mautic.integrations.helper.config_integrations'] = $instance = new \Mautic\IntegrationsBundle\Helper\ConfigIntegrationsHelper(${($_ = isset($this->services['mautic.integrations.helper']) ? $this->services['mautic.integrations.helper'] : $this->getMautic_Integrations_HelperService()) && false ?: '_'});

$instance->addIntegration(${($_ = isset($this->services['grapesjsbuilder.integration.configuration']) ? $this->services['grapesjsbuilder.integration.configuration'] : ($this->services['grapesjsbuilder.integration.configuration'] = new \MauticPlugin\GrapesJsBuilderBundle\Integration\Support\ConfigSupport())) && false ?: '_'});

return $instance;
