<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.report.model.file_handler' shared service.

return $this->services['mautic.report.model.file_handler'] = new \Mautic\ReportBundle\Scheduler\Model\FileHandler(${($_ = isset($this->services['mautic.helper.file_path_resolver']) ? $this->services['mautic.helper.file_path_resolver'] : $this->getMautic_Helper_FilePathResolverService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.file_properties']) ? $this->services['mautic.helper.file_properties'] : ($this->services['mautic.helper.file_properties'] = new \Mautic\CoreBundle\Helper\FileProperties())) && false ?: '_'}, ${($_ = isset($this->services['mautic.helper.core_parameters']) ? $this->services['mautic.helper.core_parameters'] : ($this->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($this))) && false ?: '_'});
