<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.install.fixture.remove_duplicate_index' shared service.

return $this->services['mautic.install.fixture.remove_duplicate_index'] = new \Mautic\InstallBundle\InstallFixtures\ORM\RemoveDuplicateIndexData();
