<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.field.notification.custom_field' shared service.

return $this->services['mautic.lead.field.notification.custom_field'] = new \Mautic\LeadBundle\Field\Notification\CustomFieldNotification(${($_ = isset($this->services['mautic.core.model.notification']) ? $this->services['mautic.core.model.notification'] : $this->getMautic_Core_Model_NotificationService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.user.model.user']) ? $this->services['mautic.user.model.user'] : $this->getMautic_User_Model_UserService()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'});
