<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.field.dispatcher.field_column_background_dispatcher' shared service.

return $this->services['mautic.lead.field.dispatcher.field_column_background_dispatcher'] = new \Mautic\LeadBundle\Field\Dispatcher\FieldColumnBackgroundJobDispatcher(${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'});
