<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.core.command.maxmind.purge' shared service.

return $this->services['mautic.core.command.maxmind.purge'] = new \Mautic\CoreBundle\Command\MaxMindDoNotSellPurgeCommand(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.maxmind.doNotSellList']) ? $this->services['mautic.maxmind.doNotSellList'] : $this->load('getMautic_Maxmind_DoNotSellListService.php')) && false ?: '_'});
