<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mautic.lead.command.create_custom_field' shared service.

return $this->services['mautic.lead.command.create_custom_field'] = new \Mautic\LeadBundle\Field\Command\CreateCustomFieldCommand(${($_ = isset($this->services['mautic.lead.field.settings.background_service']) ? $this->services['mautic.lead.field.settings.background_service'] : $this->load('getMautic_Lead_Field_Settings_BackgroundServiceService.php')) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['mautic.lead.repository.field']) ? $this->services['mautic.lead.repository.field'] : $this->getMautic_Lead_Repository_FieldService()) && false ?: '_'});
