<?php /** @var $block Colissimo\Shipping\Block\Adminhtml\Price\Import **/ ?>
<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Prix">
            <div class="page-actions-buttons">
                <button id="back" type="button" class="action- scalable back" onclick="location.href = '<?php echo $backUrl; ?>';">
                    <span><?php echo __('Back') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="colissimo-price-uploader">
    <div class="colissimo-price-step">
        <h2><?php echo __('Select file to import:') ?></h2>
        <div id="<?php echo $htmlId; ?>-container" class="colissimo-price-files" data-mage-init='{"baseImage":{}}' data-max-file-size="<?php echo $fileMaxSize; ?>">
            <div class="image image-placeholder">
                <input type="file"
                       name="file"
                       data-url="<?php echo $uploadUrl; ?>"
                       multiple="multiple" />
                <p class="image-placeholder-text"><?php echo $filePlaceholderText; ?></p>
            </div>
            <script id="<?php echo $htmlId; ?>-template"
                    data-template="image"
                    type="text/x-magento-template">
                <div class="import-file" onclick="Price.file('<%- data.file %>', this)">
                    <%- data.file %>
                </div>
            </script>
        </div>
        <h2><?php echo __('Options:') ?></h2>
        <div class="colissimo-price-options">
            <label for="colissimo-price-mode"><?php echo __('Mode:') ?></label>
            <select id="colissimo-price-mode" name="mode">
                <option value="<?php echo $block->getModeErase() ?>" selected><?php echo __('Erase') ?></option>
                <option value="<?php echo $block->getModeAppend() ?>"><?php echo __('Append') ?></option>
            </select>
        </div>
        <div id="media_gallery_content"></div>
    </div>
    <div class="colissimo-price-step step-last">
        <button type="button" class="primary" onclick="Price.run()">
            <span class="ui-button-text">
                <span><?php echo __('Launch import') ?></span>
            </span>
        </button>
    </div>
</div>

<div class="colissimo-price-result waiting"><?php echo __('Waiting...') ?></div>

<script>
    require(
        ["Colissimo_Shipping/js/import"],
        function(price) {
            price.init('<?php echo $runUrl; ?>', '.colissimo-price-result');
            window.Price = price;
        }
    );
</script>