<?php /** @var $block \Amasty\Feed\Block\Adminhtml\Feed\Edit\Tab\Buttons\TestConnection */ ?>
<div class="feed-test-connection">
    <?= $block->getButtonHtml() ?>
    <p class="feed-connection-result"></p>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Amasty_Feed/js/feed/testConnection": {
                    "ajaxUrl": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>"
            }
        }
    }
</script>
