<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<?php
$fields = $block->getCustomFields();
?>
<p style="text-transform: uppercase"><?= $block->escapeHtml(__('Extra Fields:')) ?></p>
<?php
if ($fields):
    foreach ($fields as $field): ?>
        <p><strong><?= $block->escapeHtml($field['label']); ?>:</strong> <?= $block->escapeHtml($field['value']); ?></p>
    <?php endforeach;
endif;?>
