<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var $block \Amasty\RequestQuote\Block\Account\Quote\Info */ ?>

<div class="actions">
    <?php $quote = $block->getQuote() ?>
    <?php if ($block->isAllowedPdf()): ?>
        <a href="#" data-post='<?= /* @noEscape */$block->getPostData($block->getDownloadPdfUrl($quote)) ?>'
           class="action order">
            <span><?= $escaper->escapeHtml(__('Download PDF')) ?></span>
        </a>
    <?php endif; ?>
    <?php if ($block->isDeleteShow($quote)): ?>
    <a href="#" data-post='<?= /* @noEscape */ $block->getPostData($block->getDeleteUrl($quote)) ?>'
       class="action order">
        <span><?= $escaper->escapeHtml(__('Delete')) ?></span>
    </a>
    <?php endif; ?>
    <?php if ($block->isCancelShowed($quote)): ?>
        <a href="#" data-post='<?= /* @noEscape */ $block->getPostData($block->getCancelUrl($quote)) ?>'
           class="action order">
        <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
        </a>
    <?php endif; ?>
</div>
