<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var \Amasty\RequestQuote\Block\Account\Quote\History $block */ ?>

<?php $quotes = $block->getQuotes(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($quotes && $quotes->getSize()): ?>
    <div class="table-wrapper quotes-history">
        <table class="data table table-quote-items history" id="my-quotes-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Quotes')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $escaper->escapeHtml(__('Quote #')) ?></th>
                <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Date')) ?></th>
                <th scope="col" class="col total"><?= $escaper->escapeHtml(__('Quote Total')) ?></th>
                <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th>
                <?php if ($block->isExpiryColumnShow()): ?>
                <th scope="col" class="col expired"><?= $escaper->escapeHtml(__('Expiry Date')) ?></th>
                <?php endif; ?>
                <th scope="col" class="col actions"><?= $escaper->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($quotes as $quote): ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtml(__('Quote #')) ?>" class="col id"><?= $escaper->escapeHtml($quote->getIncrementId()) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Date')) ?>" class="col date"><?= $escaper->escapeHtml($block->formatDate($quote->getCreatedAt())) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Quote Total')) ?>" class="col total"><?= /* @noEscape */ $quote->formatPrice($quote->getGrandTotal()) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>" class="col status"><?= $escaper->escapeHtml($quote->getStatusLabel())?></td>
                    <?php if ($block->isExpiryColumnShow()): ?>
                    <td data-th="<?= $escaper->escapeHtml(__('Expiry Date')) ?>" class="col expired"><?= $escaper->escapeHtml($block->getExpiredDate($quote)) ?></td>
                    <?php endif; ?>
                    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= $escaper->escapeUrl($block->getViewUrl($quote)) ?>" class="action view">
                            <span><?= $escaper->escapeHtml(__('View')) ?></span>
                        </a>
                    <?php if ($block->isMoveShowed($quote)): ?>
                        <a href="#" data-post='<?= /* @noEscape  */$block->getPostData($block->getMoveUrl($quote)) ?>'
                           class="action quote" title="<?= $escaper->escapeHtml(__('Move to Cart')) ?>">
                                <span><?= $escaper->escapeHtml(__('Move to Cart')) ?></span>
                        </a>
                    <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="quote-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have placed no quotes.')) ?></span></div>
<?php endif ?>
