<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var $block \Amasty\RequestQuote\Block\Account\Quote\Info */ ?>

<div class="order-date">
    <span><?= $escaper->escapeHtml(__('Creation Date:')) ?></span>
    <date><?= $escaper->escapeHtml($block->formatDate($block->getQuote()->getCreatedAt(), \IntlDateFormatter::LONG)) ?></date>
</div>

<?php if ($block->isExpiryColumnShow()): ?>
    <div class="order-date">
        <span><?= $escaper->escapeHtml(__('Expiry Date:')) ?></span>
        <date><?= $escaper->escapeHtml($block->getExpiredDate()) ?></date>
    </div>
<?php endif; ?>
