<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<section class="admin__page-section edit-order-comments">
    <ul class="note-list">
    <?php foreach ($block->getFullHistory() as $item): ?>
        <li class="note-list-item">
            <span class="note-list-date"><?= /* @noEscape */ $block->getItemCreatedAt($item) ?></span>
            <span class="note-list-time"><?= /* @noEscape */ $block->getItemCreatedAt($item, 'time') ?></span>
            <span class="note-list-status"><?= /* @noEscape */ $block->getItemTitle($item) ?></span>
            <?php if ($block->isItemNotified($item, false)): ?>
                <span class="note-list-customer">
                    <?= /* @noEscape */ __('Customer') ?>
                    <?php if ($block->isCustomerNotificationNotApplicable($item)): ?>
                        <span class="note-list-customer-notapplicable"><?= /* @noEscape */ __('Notification Not Applicable') ?></span>
                    <?php elseif ($block->isItemNotified($item)): ?>
                        <span class="note-list-customer-notified"><?= /* @noEscape */ __('Notified') ?></span>
                    <?php else: ?>
                        <span class="note-list-customer-not-notified"><?= /* @noEscape */ __('Not Notified') ?></span>
                    <?php endif; ?>
                </span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <div class="edit-order-comments-block">
        <div class="edit-order-comments-block-title">
            <?= /* @noEscape */ __('Notes for this Quote') ?>
        </div>
        <?php foreach ($block->getFullHistory() as $item): ?>
            <?php if ($_comment = $block->getItemComment($item)): ?>
                <div class="comments-block-item">
                    <div class="comments-block-item-comment">
                        <?= /* @noEscape */ $_comment ?>
                    </div>
                    <span class="comments-block-item-date-time">
                        <?= /* @noEscape */ __('Comment added') ?>
                        <?= /* @noEscape */ $block->getItemCreatedAt($item) ?>
                        <?= /* @noEscape */ $block->getItemCreatedAt($item, 'time') ?>
                    </span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</section>
