<?php
/** @var $block \Netreviews\Avisverifies\Block\Product\ReviewRenderer */
$getRichSnippets = $block->getRichSnippets();
$richSnippetsAlreadyExist = $block->isRichSnippetsAlreadyExist();
$price = ($block->product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) ? $block->product->getFinalPrice() : $block->product->getPrice();
?>
<?php if($block->nbReviews > 0 ):?>
    <div class="netreviews-stars">
        <span>
            <div class="netreviews_bg_stars_big headerStars" title="<?php echo $block->rateFormated; ?>/5">
                <?php echo $block->ntavAddStarsByRate ?>
            </div>
            <a    class="netreviews-stars-link" rel="nofollow"><span><?php echo $block->nbReviews; ?></span>&nbsp;<?php echo __('review(s)'); ?></a>
        </span>
    </div>

    <?php if($getRichSnippets == "schema"): ?>
        <meta itemprop="description" content="<?= $block->escapeHtml($block->product->getDescription()) ?>">
        <meta itemprop="image" content="<?= $block->escapeHtml($block->productHelper->getImageUrl($block->product)) ?>" />
        <meta itemprop="url" content="<?= $block->escapeHtml($block->productHelper->getProductUrl($block->product)) ?>" />
        <meta itemprop="productID" content="<?= $block->product->getId() ?>" />
        <meta itemprop="brand" content="<?= $block->escapeHtml($block->getAttributProductByPlaConfig('brand')) ?>" />
        <meta itemprop="mpn" content="<?= $block->escapeHtml($block->getAttributProductByPlaConfig('mpn')) ?>" />
        <meta itemprop="gtin8" content="<?= $block->escapeHtml($block->getAttributProductByPlaConfig('gtin_ean')) ?>" />
        <meta itemprop="gtin12" content="<?= $block->escapeHtml($block->getAttributProductByPlaConfig('gtin_upc')) ?>" />
        <div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
            <meta itemprop="ratingValue" content="<?= $block->rateFormated; ?>"/>
            <meta itemprop="worstRating" content="1"/>
            <meta itemprop="bestRating" content="5"/>
            <meta itemprop="ratingCount " content="<?= $block->nbReviews; ?>"/>
        </div>

    <?php elseif($getRichSnippets == "jsonld"): ?>
        <script type="application/ld+json">
            {
                "@context": "http://schema.org/",
                "@type": "Product",
                "@id": "<?= $block->escapeHtml($block->product->getId()) ?>",
                "name": "<?= $block->escapeHtml($block->product->getName()) ?>",
                <?php if( $richSnippetsAlreadyExist == 0 ):?>
                    "description": "<?= $block->escapeHtml($block->product->getDescription()) ?>",
                    "offers":
                      [
                         {
                            "@type": "Offer",
                            "priceCurrency": "<?= $block->getCurrentCurrency(); ?>",
                            "price": "<?= $price ?>",
                            "availability": "http://schema.org/InStock",
                            "name": "<?= $block->escapeHtml($block->product->getName()) ?>",
                            "url": "<?=  $block->escapeHtml($block->product->getProductUrl()); ?>>"
                         }
                      ],
                    "url": "<?= $block->escapeHtml($block->product->getProductUrl()) ?>",
                    "brand": "<?= $block->escapeHtml($block->getAttributProductByPlaConfig('brand')) ?>",
                    "productID": "<?= $block->escapeHtml($block->product->getId()) ?>",
                    "sku": "<?= $block->escapeHtml($block->product->getSku()) ?>",
                    "mpn": "<?= $block->escapeHtml($block->getAttributProductByPlaConfig('mpn')) ?>",
                    "gtin8": "<?= $block->escapeHtml($block->getAttributProductByPlaConfig('gtin_ean')) ?>",
                    "gtin12": "<?= $block->escapeHtml($block->getAttributProductByPlaConfig('gtin_upc')) ?>",
                <?php endif;?>
                "aggregateRating": {
                    "@type": "AggregateRating",
                    "ratingValue": "<?= $block->escapeHtml($block->rateFormated); ?>",
                    "reviewCount": "<?= $block->escapeHtml($block->nbReviews); ?>",
                    "worstRating": "1",
                    "bestRating": "5"
                }
            }
        </script>
    <?php endif;?>
<?php endif;?>
