<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var \Amasty\RequestQuote\Block\Adminhtml\Quote\Create\Data $block */

// @codingStandardsIgnoreFile

?>
<div class="page-create-order">
    <script>
        require(["Amasty_RequestQuote/quote/create/form"], function(){
            quote.setCurrencySymbol('<?= /* @noEscape */ $block->getCurrencySymbol($block->getCurrentCurrencyCode()) ?>')
        });
    </script>
    <div class="order-details<?php if ($block->getCustomerId()): ?> order-details-existing-customer<?php endif; ?>">

        <div id="order-additional_area" style="display: none" class="admin__page-section order-additional-area">
            <?= $block->getChildHtml('additional_area') ?>
        </div>

        <div id="quote-search" style="display: none" class="admin__page-section order-search-items">
            <?= $block->getChildHtml('search') ?>
        </div>

        <section id="quote-items" class="admin__page-section order-items" data-mage-init='{"loader": {}}'>
            <?= $block->getChildHtml('items') ?>
        </section>

        <div id="order-errors" class="order-errors"><?= $block->getChildHtml('errors') ?></div>

        <section id="order-form_account" class="admin__page-section order-account-information">
            <?= $block->getChildHtml('form_account') ?>
        </section>

        <div class="admin__field admin__field-option">
            <input name="quote[shipping_configured]" type="checkbox" id="shipping_configured" value="1"<?php if ($block->isShippingConfigured()): ?> checked="checked"<?php endif; ?>
                   class="admin__control-checkbox"
                   onchange="quote.configureShipping(this.checked) "/>
            <label for="shipping_configured" class="admin__field-label"><?= $escaper->escapeHtml(__('Configure Shipping')) ?></label>
        </div>

        <section id="quote-addresses" class="admin__page-section order-addresses" data-amquote-js="quote_addresses">
            <div class="admin__page-section-title">
                <span class="title"><?= $escaper->escapeHtml(__('Address Information')) ?></span>
            </div>
            <div class="admin__page-section-content">
                <div id="order-billing_address" class="admin__page-section-item order-billing-address">
                    <?= $block->getChildHtml('billing_address') ?>
                </div>
                <div id="quote-shipping_address" class="admin__page-section-item order-shipping-address">
                    <?= $block->getChildHtml('shipping_address') ?>
                </div>
            </div>
        </section>

        <section id="quote-methods" class="admin__page-section order-methods" data-amquote-js="shipping_methods">
            <div class="admin__page-section-title">
                <span class="title"><?= $escaper->escapeHtml(__('Shipping Information')) ?></span>
            </div>
            <div class="admin__page-section-content">
                <div id="quote-shipping_method" class="admin__page-section-item quote-shipping-method">
                    <?= $block->getChildHtml('shipping_method') ?>
                </div>
            </div>
        </section>

        <?php if ($block->getChildBlock('card_validation')): ?>
            <section id="order-card_validation" class="admin__page-section order-card-validation">
                <?= $block->getChildHtml('card_validation') ?>
            </section>
        <?php endif; ?>

        <section class="admin__page-section order-summary">
            <div class="admin__page-section-title">
                <span class="title"><?= /* @noEscape */ __('Quote Total') ?></span>
            </div>
            <div class="admin__page-section-content">
                <fieldset class="admin__fieldset order-history" id="order-comment">
                    <legend class="admin__legend"><span><?= /* @noEscape */ __('Quote History') ?></span></legend>
                    <br>
                    <?= $block->getChildHtml('comment') ?>
                </fieldset>
                <fieldset id="quote-totals" class="admin__fieldset order-totals">
                    <?= $block->getChildHtml('totals') ?>
                </fieldset>
            </div>
        </section>
    </div>

    <?php if ($block->getCustomerId()): ?>
        <div class="order-sidebar">
            <div class="store-switcher order-currency">
                <label class="admin__field-label" for="currency_switcher">
                    <?= /* @noEscape */ __('Quote Currency:') ?>
                </label>
                <select id="currency_switcher"
                        class="admin__control-select"
                        name="order[currency]"
                        onchange="quote.setCurrencyId(this.value); quote.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
                    <?php foreach ($block->getAvailableCurrencies() as $_code): ?>
                        <option value="<?= /* @noEscape */ $_code ?>"<?php if ($_code == $block->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?> symbol="<?= /* @noEscape */ $block->getCurrencySymbol($_code) ?>">
                            <?= /* @noEscape */ $block->getCurrencyName($_code) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="customer-current-activity" id="order-sidebar">
                <?= $block->getChildHtml('sidebar') ?>
            </div>
        </div>
    <?php endif; ?>

</div>
