<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var $block \Amasty\RequestQuote\Block\Quote\Success */ ?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()): ?>
    <a href="<?= /* @noEscape */ $block->getPrintUrl() ?>" target="_blank" class="print">
        <?= /* @noEscape */ __('Print receipt') ?>
    </a>
    <?= $block->getChildHtml() ?>
<?php endif;?>
