<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/** @var $block \Amasty\RequestQuote\Block\Quote\Success */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="checkout-success">
    <?php if ($block->getQuoteId()):?>
        <p class="quote-interest-message"><?= /* @noEscape */ __('Thank you for your interest!') ?></p>
        <?php if ($block->getCanViewQuote()): ?>
            <p><?= /* @noEscape */ __('Your Quote Request # is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $escaper->escapeHtml($block->getViewQuoteUrl()), $escaper->escapeHtml($block->getQuoteId()))) ?></p>
        <?php else: ?>
            <p><?= /* @noEscape */ __('Your Quote Request # is: <span>%1</span>.', $escaper->escapeHtml($block->getQuoteId())) ?></p>
        <?php endif;?>
        <p><?= /* @noEscape */ __('We\'ll email you a Quote Request confirmation email with a link to track progress.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $escaper->escapeUrl($block->getContinueUrl()) ?>"><span><?= /* @noEscape */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
