<?php
/**
 * @var $block \Gone\GoogleTag\Block\GoogleTag
 */
$gtagID = $block->getGoogleTagId();
?>

<?php if ($gtagID) : ?>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=<?= $gtagID ?>"
                height='0' width='0' style='display:none;visibility:hidden'></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
<?php endif; ?>
