<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement(EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_MauticIntegration
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CEDCOMMERCE(http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

/* @var $block \Ced\MauticIntegration\Block\Adminhtml\System\Config\GenerateCode */
?>

    <script type="text/x-magento-init">
     {
        "*" :{
        "Ced_MauticIntegration/js/generate_code":{
           "GenerateCodeAjaxUrl" : "<?php /* @escapeNotVerified */ echo $block->getAjaxSyncUrl(); ?>"
                 }
             }
        }


</script>


<?php echo $block->getButtonHtml(); ?>