<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Abandoned Cart Email Base for Magento 2
 */
/**
 * @var \Amasty\Acart\Block\Email\Items $block
 * @var \Magento\Catalog\Api\Data\ProductInterface $product
 * @var \Amasty\Acart\ViewModel\Email\ProductViewModel $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */
$viewModel = $block->getData('viewModel');
?>
<?php foreach ($block->getItems() as $item): ?>
    <?php $product = $viewModel->getProduct($item, $block->showConfigurableImage()); ?>
    <a class="acart-product-card acart-link -list" href="<?= $escaper->escapeUrl($viewModel->getProductUrl($product)); ?>">
        <?= $block->getItemBlockHtml($item); ?>
    </a>
<?php endforeach; ?>
