<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php
/**  @var $block \Amasty\RequestQuote\Block\Cart */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="cart-empty">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= /* @noEscape */ __('You have no items in your quote cart.') ?></p>
    <p><?= /* @noEscape */ __('Click <a href="%1">here</a> to continue shopping.', $escaper->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
