<?php
/**
 * @var $block Showroom
 */

use Gone\Catalog\Block\Product\View\Showroom;

$isInShowroom = $block->getIsInShowroom();
?>
<?php if ($isInShowroom): ?>
    <hr>
    <div class="showroom-information">
   <span>
       <?= __('Are you interested in %1 ?', $block->getProduct()->getName()) ?>
   </span>
        <p>
            <?= __('This product is visible in our showroom. Please, ask for a demo via our contact form.') ?>
        </p>
    </div>
<?php endif; ?>
