<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_RequestQuote
 */
?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php if ($block->canDisplayGiftmessage()): ?>
<?php $required = $block->getMessage()->getMessage() != ''?>
<div id="<?= $block->getHtmlId() ?>" class="admin__page-section-content giftmessage-whole-order-container">
    <form class="entry-edit form-inline" id="<?= /* @noEscape */ $block->getFieldId('form') ?>" action="<?= /* @noEscape */ $block->getSaveUrl() ?>">
        <fieldset class="admin__fieldset">
            <legend class="admin__legend"><span><?= /* @noEscape */ __('Gift Message for the Entire Order') ?></span></legend>
            <br/>

            <input type="hidden" id="<?= /* @noEscape */ $block->getFieldId('type') ?>"
                   name="<?= $escaper->escapeHtml($block->getFieldName('type')) ?>"
                   value="order"/>

            <div class="admin__field field-from-name<?= $required ? ' required' : '' ?>">
                <label class="admin__field-label"
                       for="<?= $escaper->escapeHtml($block->getFieldId('sender')) ?>"><span><?= /* @noEscape */ __('From Name') ?></span></label>

                <div class="admin__field-control">
                    <input class="admin__control-text <?= $required ? 'required-entry' : '' ?>" type="text"
                           id="<?= $escaper->escapeHtml($block->getFieldId('sender')) ?>"
                           name="<?= $escaper->escapeHtml($block->getFieldName('sender')) ?>"
                           value="<?= $escaper->escapeHtml($block->getMessage()->getSender()) ?>"/>
                </div>
            </div>

            <div class="admin__field field-to-name<?= $required ? ' required' : '' ?>">
                <label class="admin__field-label"
                       for="<?= $escaper->escapeHtml($block->getFieldId('recipient')) ?>"><span><?= /* @noEscape */ __('To Name') ?></span></label>

                <div class="admin__field-control">
                    <input class="admin__control-text <?= $required ? 'required-entry' : '' ?>" type="text"
                           id="<?= $escaper->escapeHtml($block->getFieldId('recipient')) ?>"
                           name="<?= $escaper->escapeHtml($block->getFieldName('recipient')) ?>"
                           value="<?= $escaper->escapeHtml($block->getMessage()->getRecipient()) ?>"/>
                </div>
            </div>

            <div class="admin__field field-gift-message">
                <label class="admin__field-label"
                       for="<?= $escaper->escapeHtml($block->getFieldId('message')) ?>"><span><?= /* @noEscape */ __('Gift Message') ?></span></label>
                <div class="admin__field-control">
                    <textarea id="<?= $escaper->escapeHtml($block->getFieldId('message')) ?>"
                              name="<?= $escaper->escapeHtml($block->getFieldName('message')) ?>"
                              class="admin__control-textarea"
                              rows="2"
                              cols="15"><?= $escaper->escapeHtml($block->getMessage()->getMessage()) ?></textarea>
                </div>
            </div>

            <div class="actions">
                <?= $block->getSaveButtonHtml() ?>
            </div>
        </fieldset>
    </form>
</div>
<?php endif ?>
